### ISSUE TITLE
Prep for online Announcement

### ISSUE THREAD

**Issue by Jacob-Mellichamp** [CUCyber/cuctf.io#24]
With the COVID-19 pandemic hitting a "second wave" optimism is low regarding having CUCTF 2020 in person. This event will most likely be online. That being said, I want to construct a branch that will better portray our intentions of hosting this event. To do this, I'm asking for the following changes:

### FAQ Questions
- [x] "where is the event being held?" --> "Is this event online?"
- [x] "How will we interact with sponsors?"
- [x] "How will an online CUCTF look compared to it's previous in person event?"

### About Page
- [x] "When and Where" section needs to be changed to say the event is online.

### Home Page
- [x] Edit *Where* to online

### Sponsor Page
- [x] Add a notification that the Contingency Plan is in place.

**Comment by lilyinstarlight** [comment]
Reference: #26

**Comment by lilyinstarlight** [comment]
Reference: #27

**Comment by Jacob-Mellichamp** [comment]
Reference #29 All FAQ Questions Answered. Closing.
